language: ruby
cache: bundler
sudo: required
rvm:
  - 2.2.3
  - rubinius
  - jruby
before_install:
  - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ trusty main universe"
  - sudo apt-get update -qq
  - sudo apt-get install libzmq3-dev
  - (cd vendor/czmq && ./autogen.sh && ./configure && make && sudo make install)
  - gem install bundler -v 1.10.6
script: bundle exec rake spec
