language: ruby
cache:
  directories:
    - vendor/bundle
    - vendor/czmq-ffi-gen
sudo: required
rvm:
  - 2.3.0
  - 2.2.4
  - jruby-head
  - rubinius
before_install:
  - ci-scripts/install-deps
  - gem install bundler -v 1.10.6
script: bundle exec rake spec
